### ISSUE TITLE
Quotes & Replies are being displayed as attachments

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat.Livechat#182]
<img width="370" alt="screen shot 2019-03-08 at 16 07 19" src="https://user-images.githubusercontent.com/20868078/54049820-6a06d300-41bc-11e9-9dc3-e3127979ed3c.png">

**Comment by abrahamks** [comment]
Hello,
I'm interested to pick up this issue. 
I have reproduced the same bug on my local machine.
<img width="1134" alt="Screen Shot 2019-03-13 at 13 51 21" src="https://user-images.githubusercontent.com/3590693/54302457-431f1700-4597-11e9-8979-e6297eaab12b.png">


I tried to look at the old version of the widget but it didn't seems have a good UI for handling quotes and replies
<img width="315" alt="Screen Shot 2019-03-13 at 13 47 53" src="https://user-images.githubusercontent.com/3590693/54302142-b3796880-4596-11e9-9e6a-deaa7baa9f51.png">

What is the expected behaviour? Do you have any UI mockups that I can look at?

**Comment by tassoevan** [comment]
@abrahamks We are waiting for a response from our design team, because there was no mockup.

**Comment by renatobecker** [comment]
Hi @abrahamks!
We have the design done now, are you still interested in this issue? If so, please let me know.

Thanks.
