### ISSUE TITLE
Popout Mode not working in RocketChat 2.0

### ISSUE THREAD

**Issue by jthomaschewski** [RocketChat/Rocket.Chat.Livechat#287]
**Faulty behavior**

- livechat is shown in default mode (non "popout") when accessing it with mode parameter: 
"https://rc.example.com/livechat?mode=popout"
Mode parameter has no effect.

**Expected behavior**

- livechat "popout" mode is activated (helpful for embedding in iFrame)

This was working fine in RC 1.3.2, both with legacy and new livechat UI.
This was possible by adding `&mode=popout` to URL.
e.g: `https://rc.example.com/livechat?mode=popout` (legacy UI) or `https://rc.example.com/livechat?version=1.0.0&mode=popout` (new UI)

This seems to be broken since `^2.0`.

Initial Implementation of this feature: https://github.com/RocketChat/Rocket.Chat/pull/1636

**Additional information**

It seems as if popout mode is implemented in the UI, in a browser session which had the LiveChat open in popout mode before updating from 1.3.2 to 2.0.0, switching modes between popout and non-popout works fine.
The switch isn't working in a clean session/incognito mode though.

**Comment by renatobecker** [comment]
@jbbr 

I just ran some tests and everything looks fine as you can see below:

Regular Livechat UI:
![Screen Shot 2019-09-17 at 16 35 33](https://user-images.githubusercontent.com/2067649/65073736-d3d11800-d969-11e9-8b30-e9dfe6d117c1.png)

Mode Popout:
![Screen Shot 2019-09-17 at 16 36 27](https://user-images.githubusercontent.com/2067649/65073749-db90bc80-d969-11e9-80c0-25930aee879a.png)

In addition, the `version=1.0.0` parameter is no longer required, since we've already deprecated the old Livechat widget, so the new one is served on the regular Livechat route.

Thanks.

**Comment by jbbr** [comment]
@renatobecker thanks for testing. I still do have the issues as described.
I tested it again by using a fresh, local install using docker.

![image](https://user-images.githubusercontent.com/682607/65147147-cecda080-da1d-11e9-972f-15594a3626a4.png)

After installing and setting up a user, I directly opened http://localhost:3000/livechat?mode=popout in a incognito window of Chrome 76.

![image](https://user-images.githubusercontent.com/682607/65147202-f02e8c80-da1d-11e9-88da-b9b63f112586.png)

**Comment by Blackskyliner** [comment]
Got the same problem here for me it's also different between Browsers. 

If I open the popout URI in my Firefox I get the "full-blown non Popout UI" on the `mode=popout` URI -- Always. (Firefox Linux 69.0.1)

I can also observe the stated behavior in Chrome if using the incognito mode. Without Incognito mode it works as intended.

**Comment by Blackskyliner** [comment]
Okay, I did some debugging. 

It seems the Store gets initialized with `minimized: true` now this gets into the render of the `App/index.js` now the check which utilized the `?mode=popout=` does check with this `minimized` variable for setting the `windowed` Property will then evaluate to `!true && true` so the setting fails to initialize the Chat in the correct mode.

Relevant Codepoint: https://github.com/RocketChat/Rocket.Chat.Livechat/blob/b0f1aa72928aae8e519c9352d577677da2ad02ea/src/components/App/index.js#L182

It seems also to be important to have a clean/empty and pristine browser state with no already saved local app-state. Thus its happening in Chrome Incognito reproducible. (And for me in Firefox because I distinctly opened the popout mode URI before ding anything else)

I did not find where the `minimized` gets initialized with `true`. Thus why I could not provide a Pull Request with this analysis. I guess this part should be rewritten so that the mode does have precedence over saved state.

**Comment by mcabrera-contenta** [comment]
This is still true. `mode=popout` only works if you previously saw the chat in its floating button state, and pressed the "Expand" button to get the chat to pop out. That seems to set something that makes de popout view work. However, if in a pristine condition you start with `mode=popout`, you get the floating button with the X to close the Chat (which does nothing). Very easy to reproduce in Incognito Mode.

**Comment by ebaioni** [comment]
we are experiencing the same issue

**Comment by renatobecker** [comment]
This issue has been fixed and released here -> https://github.com/RocketChat/Rocket.Chat.Livechat/releases/tag/v1.7.6
